/*
 * https://en.cppreference.com/w/cpp/language/types
 * */

export enum TypeSpecifier {
  AUTO = "auto",
  SHORT = "short",
  SHORT_INT = "shortint",
  SIGNED_SHORT = "signedshort",
  SIGNED_SHORT_INT = "signedshortint",
  UNSIGNED_SHORT = "unsignedshort",
  UNSIGNED_SHORT_INT = "unsignedshortint",
  INT = "int",
  SIGNED = "signed",
  SIGNED_INT = "signedint",
  UNSIGNED = "unsigned",
  UNSIGNED_INT = "unsignedint",
  LONG = "long",
  LONG_INT = "longint",
  SIGNED_LONG = "signedlong",
  SIGNED_LONG_INT = "signedlongint",
  UNSIGNED_LONG = "unsignedlong",
  UNSIGNED_LONG_INT = "unsignedlongint",
  LONG_LONG = "longlong",
  LONG_LONG_INT = "longlongint",
  SIGNED_LONG_LONG = "signedlonglong",
  SIGNED_LONG_LONG_INT = "signedlonglongint",
  UNSIGNED_LONG_LONG = "unsignedlonglong",
  UNSIGNED_LONG_LONG_INT = "unsignedlonglongint",
  SIGNED_CHAR = "signedchar",
  UNSIGNED_CHAR = "unsignedchar",
  CHAR = "char",
  WCHAR_T = "wchart",
  CHAR8_T = "char8t",
  CHAR16_T = "char16t",
  CHAR32_T = "char32t",
  FLOAT = "float",
  DOUBLE = "double",
  LONG_DOUBLE = "longdouble",
  VOID = "void",
}

export enum KeyWords {
  AUTO = "auto",
  Null = "null",
  CHAR = "char",
  CHAR16 = "char16",
  CHAR32 = "char32",
  WCHAR = "wchar",
  BOOL = "bool",
  SHORT = "short",
  INT = "int",
  LONG = "long",
  SIGNED = "signed",
  UNSIGNED = "unsigned",
  FLOAT = "float",
  DOUBLE = "double",
  VOID = "void",
}
