export enum CppTypes {
  CHAR = "char",
  CHAR16 = "char16",
  CHAR32 = "char32",
  WCHAR = "wchar",
  BOOL = "bool",
  SHORT = "short",
  INT = "int",
  LONG = "long",
  SIGNED = "signed",
  UNSIGNED = "unsigned",
  FLOAT = "float",
  DOUBLE = "double",
  VOID = "void",
}
